config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  devise_for :users, controllers: { 
                                :sessions => "users/sessions",
                                :registrations => "users/registrations"
                                  }
  resources :fmodels
  resources :users, :only => [:show, :index]
  # resources :follows, only: [:destroy, :create] # allows following/unfollowing
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "index#index"

  match '/users/:id', to: 'users#show', via: 'get'
  # destroy user
  match '/users/:id', to: 'users#destroy', via: 'delete'
  match '/follows', to: 'follows#create', via: 'post'
  match '/follows/:id', to: 'follows#create', via: 'post'
  match '/follows/:id', to: 'follows#destroy', via: 'delete'

  get 'fmodels/:id/analysis', to: 'fmodels#analysis', as: 'analysis_results'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  isAdmin                :boolean          default(FALSE)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  paginates_per = 10  #set pagination limit
  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  
  def canModify
    User.current.present? && (User.current.id == self.id || User.current.isAdmin)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    redirect_to new_user_session_path
  end

  # # POST /resource
  # def create
  #   super
  # end

  # POST /resource
  def create
    # super
    super do |resource|
      if !resource.persisted?
        flash[:notice] = flash[:notice].to_a.concat resource.errors.full_messages
        redirect_back fallback_location: root_path and return
      end
    end
  end

  # def build_resource(hash=nil)
  #   super
  #   @sign_up_user = self.resource
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super do |resource|
      if resource.id != current_user.id || !current_user.isAdmin
        flash[:notice] =  "You do not have permission to edit this user."
        redirect_back fallback_location: root_path and return
      end

      if !resource.errors.empty?
        puts "failed to save user \n\n\n"
        flash[:notice] = flash[:notice].to_a.concat resource.errors.full_messages
        redirect_back fallback_location: root_path and return        
      else
        flash[:notice] = "#{resource.username}'s profile was successfully updated."
        redirect_back fallback_location: root_path and return
      end
    end
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  #   # devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
  # end
  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @header = "Welcome"
    @title = "Login"

    super
  end

  # POST /resource/sign_in
  def create
    puts params
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :getPublicModelsForUser,
                :getPrivateModelsForUser,
                :getFollowingModelsForUser,
                :getFollowingForUser,
                :getFollowersForUser,
                :getModelsVisibleForUser

  def index
    if params[:search].present? && params[:search] != ""
      @users = User.where("LOWER(username) LIKE ?", "%#{params[:search]}%")
    else
      @users = User.all
    end

    if params[:sort].present?
      case params[:sort]
      when "num_models_asc"
      @users = @users.sort_by { |user| getModelsVisibleForUser(user).count }
      when "num_models_desc"
      @users = @users.sort_by { |user| getModelsVisibleForUser(user).count }.reverse
      when "date_joined_asc"
      @users = @users.order(:created_at)
      when "date_joined_desc"
      @users = @users.order(:created_at).reverse
      when "num_followers_asc"
      @users = @users.sort_by { |user| Follow.where(follows: user.id).count }
      when "num_followers_desc"
      @users = @users.sort_by { |user| Follow.where(follows: user.id).count }.reverse
      else
      @users = @users.order(:created_at)
      end
    else
      @users = @users.order(:created_at)
    end

    @totalUsers = @users.count
    @users = Kaminari.paginate_array(@users).page(params[:page])
    
    current_page_range = (@users.offset_value + 1)..(@users.offset_value + @users.length)
    @currentlyViewing = "#{current_page_range.first}-#{current_page_range.last} of #{@totalUsers}"

    @title = "All users"
    @header = "Users"

    @hasReturn = true

    @hasSearch = true
    @searchObject = "Users"
    @placeholder = "Input username..."

    @hasDropdown = true
    @dropdownOptions = {
      "# Models (Ascending)" => "num_models_asc",
      "# Models (Descending)" => "num_models_desc",
      "Date joined (Ascending)" => "date_joined_asc",
      "Date joined (Descending)" => "date_joined_desc",
      "# Followers (Ascending)" => "num_followers_asc",
      "# Followers (Descending)" => "num_followers_desc"
    }
    @path = users_path
  end

  def show
    # is user viewing themselves or another user?
    @user = User.find_by_id(params[:id])
    
    @viewingSelf = (current_user.present? && (current_user.id.to_i == params[:id].to_i))
    
    if @viewingSelf
      @editable = true
    elsif !current_user.present?
      puts "User not logged in"
      @editable = false
    else
      @editable = helpers.admin

      @isUserFollowingTarget = Follow.find_by(user: current_user.id, follows: @user.id)
      @isTargetFollowingUser = Follow.find_by(user: @user.id, follows: current_user.id)
    end

    if helpers.admin || @viewingSelf
      @fmodels = Fmodel.where(created_by: @user.id).order(:created_at)
    else
      @fmodels = Fmodel.where(created_by: @user.id, visibility: :global).order(:created_at)
    end

    totalFmodels = @fmodels.size

    @fmodels = Kaminari.paginate_array(@fmodels).page(params[:models_page])

    current_page_range = (@fmodels.offset_value + 1)..(@fmodels.offset_value + @fmodels.length)
    @currentlyViewing = "#{current_page_range.first}-#{current_page_range.last} of #{totalFmodels}"

    @following = Follow.where(user: @user.id).page params[:following_page]
    @followers = Follow.where(follows: @user.id).page params[:followers_page]

    @activeTab = params[:tab].present? ? params[:tab] : "following"

    @followingTotal = Follow.where(user: @user.id).count
    @followersTotal = Follow.where(follows: @user.id).count

    @hasReturn = true

    @title = @viewingSelf ? "My Profile" : "#{@user.username}'s Profile"
    @header = @user.username
  end

  def destroy
    puts "Destroying user"
    @user = User.find_by_id(params[:id])
    puts "Destorying '#{@user.username}'"

    if @user.present?
      # remove all follows/following for user
      Follow.where(user: @user.id).destroy_all
      Follow.where(follows: @user.id).destroy_all

      # delete all private and followers models
      Fmodel.where(created_by: @user.id, visibility: :unlisted).destroy_all
      Fmodel.where(created_by: @user.id, visibility: :followers).destroy_all

      # for public models, remove user
      Fmodel.where(created_by: @user.id, visibility: :global).each do |model|
        model.created_by = nil
        model.save
      end

      # finally delete user

      # remove user
      @user.destroy
    end
    # wipe session
    session[:user_id] = nil
    redirect_to root_path :notice => "Your account was deleted."
  end

  protected

  def getModelsVisibleForUser(user)
    # if user follows self.user, return all models that are global or followers
    # if user does not follow self.user, return all models that are global
    # if user is self.user, return all models
    if !current_user.present?
      @models = Fmodel.where(created_by: user.id, visibility: :global)
    elsif (current_user.id == user.id || helpers.admin)
      @models = Fmodel.where(created_by: user.id)
    elsif Follow.find_by(user: current_user.id, follows: user.id)
      @models = Fmodel.where(created_by: user.id).where("visibility = 0 OR visibility = 2")
    else
      @models = Fmodel.where(created_by: user.id, visibility: :global)
    end
  end

  def getPublicModelsForUser(user)
    @models = Fmodel.where(created_by: user.id, visibility: :global)
  end

  def getPrivateModelsForUser(user)
    @models = Fmodel.where(created_by: user.id, visibility: :unlisted)
  end

  def getFollowingModelsForUser(user)
    @models = Fmodel.where(created_by: user.id, visibility: :followers)
  end

  def getFollowingForUser(user)
    @following = Follow.where(user: user.id)
  end

  def getFollowersForUser(user)
    @followers = Follow.where(follows: user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<%= form_for(resource, as: resource_name, url: user_registration_path(resource), html: { method: :put }) do |f| %>
  <div class="field form-floating mb-3">
    <%= f.email_field :email, class: "form-control", autocomplete: "email", placeholder: "example@email.com", disabled: true %>
    <%= f.label :email, id: "user_email_label" %>
  </div>

  <div class="field form-floating mb-3">
    <%= f.text_field :username, class: "form-control", placeholder: "username", disabled: true %>
    <%= f.label :username, id: "user_username_label" %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <hr class="my-2" style="display: none;"  id="separator1">

  <div class="field form-floating mb-3">
    <%= f.password_field :password, class: "form-control", autocomplete: "new-password", placeholder: "Password", disabled: true, hidden: true %>
    <%= f.label :password, hidden: true, id: "user_password_label" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field form-floating mb-3">
    <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "new-password", disabled: true, hidden: true %>
    <%= f.label :password_confirmation, hidden: true, id: "user_password_confirmation_label" %>
    <div id="passwordHelp" class="form-text" style="display: none;">Leave blank if you don't want to change it.</div>
  </div>

  <hr class="my-2" style="display: none;" id="separator2">

  <div class="field form-floating mb-3">
    <%= f.password_field :current_password, class: "form-control", autocomplete: "current-password", aria_described_by: "confirm", disabled: true, hidden: true %>
    <%= f.label :current_password, hidden: true, id: "user_current_password_label" %>
    <div id="confirm" class="form-text" style="display: none;">Insert password to confirm changes.</div>
  </div>

  <div class="actions d-flex justify-content-between">
    <%= f.submit "Update", class: "btn btn-success", id: "submit", disabled: true, hidden: true%>
    <%# add button to delete %>
    
    <button type="button" onclick="deleteUser()" class="btn btn-danger" id="delete" disabled="true" hidden="true">Delete my profile</button>
  </div>

<% end %>

<%# hidden form to delete via destory user path %>
<form method="post" action="<%= user_path(@user) %>" id="delete-form">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete" class="btn btn-danger" id="delete" hidden>
</form>

<script>
  function deleteUser() {
    // prevent normal button action
    event.preventDefault();
    if (confirm("Are you sure?")) {
      // if true, route to delete action
      document.getElementById("delete-form").submit();
    }
  }
</script>

app/views/users/_followers.html.erb
<table class="mb-3 w-100">
  <% if users.size == 0 %>
    <tr>
      <% if tab == "following" %>
        <td><%= @viewingSelf ? "You aren't" : "#{@user.username} isn't"%> following anyone!</td>
      <% else %>
        <td><%= @viewingSelf ? "You don't have" : "#{@user.username} doesn't have"%> any followers!</td>
      <% end %>
    </tr>
  <% else %>
    <% users.each do |f| %>
      <tr>
        <td>
          <%= (tab == "following") ? f.getUsernameTarget : f.getUsernameOrigin %>
        </td>
        <td class="text-end d-flex justify-content-end">
          <%= button_to(user_path((tab == "following") ? f.follows : f.user),
              method: :get, class: "btn btn-primary btn-sm",
              'aria-label' => "View #{(tab == "following") ? f.getUsernameTarget : f.getUsernameOrigin}'s profile",
              ) do %>
            <i class="bi bi-person-fill"></i>
          <% end %>
          <% if @user.canModify %>
            <%= button_to("/follows/#{(tab == "following") ? f.follows : f.user}",
                method: :delete,
                class: "btn btn-danger btn-sm ml-2",
                'aria-label' => (tab == "following") ? "Unfollow #{f.getUsernameTarget}" : "Remove #{f.getUsernameOrigin} as a follower",
                ) do %>
              <i class="bi bi-x-lg"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <% if users.size < 10 %>
      <% (10-users.size).times do %>
        <tr class="borderless-cell" style="visibility: hidden;"><td class="borderless-cell" style="visibility: hidden;">blank</td></tr>
      <% end %>
    <% end %>
  <% end %>
</table>
<div class="flex-grow-1"></div>
<div class="d-flex justify-content-center">
  <%= paginate users, param_name: (tab == "following") ? :following_page : :followers_page,
                :params => { :tab => tab },
                theme: 'bootstrap-5',
                pagination_class: "pagination-sm flex-wrap justify-content-center",
                nav_class: "d-inline-block"
  %>
</div>
<% if @editable && tab == "following" %>
  <div class="">
    <div class="d-flex align-items-baseline">
      <div class="mr-2">
        <h6 class="px-2">Follow user:</h6>
      </div>
      <div>
        <%= form_with(url: follows_path(Follow.new), method: :post) do |f| %>
          <div class="field form-floating mb-3">
            <%= f.text_field :username, class: "form-control", placeholder: "username" %>
            <%= f.label :username %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_stats.html.erb
<div>
  <p><%= @user.username %> joined SPO
    <% if (Time.now - @user.created_at) >= 2.days %>
      on
    <% end %>
    <%= formatTime(@user.created_at) %>.
  </p>
  <p>They have created <%= @fmodels.size %> models.</p>
  
  <hr>

  <% if current_user.present? %>
    <% if @isUserFollowingTarget %>
      <p>You started following <%= @user.username %>
        <% if (Time.now - @isUserFollowingTarget.created_at) >= 2.days %>
          on
        <% end %>
        <%= formatTime(@isUserFollowingTarget.created_at).downcase %>.
      </p>
    <% else %>
      <div class="d-flex align-items-center">
        <%= button_to(follows_path,
            method: :post,
            params: { id: @user.id },
            class: "btn btn-primary btn-sm mr-2") do%>
          <i class="bi bi-person-plus-fill"></i>
        <% end %>
        <p class="mb-0">Follow <%= @user.username %></p>
      </div>
    <% end %>
    <% if @isTargetFollowingUser %>
      <p><%= @user.username %> follows you<%= @isUserFollowingTarget ? " back" : ""%>!</p>
    <% end %>
  <% else %>
    <p>Join SPO to follow <%= @user.username %>.</p>
  <% end %>
  
  <hr>
  
</div>

app/views/users/index.html.erb
<div id="users">

  <table class="w-100 table table-sm table-hover">
    <% if @users.size == 0 %>
      <tr>
        <td>No users found, how did that even happen?</td>
      </tr>
    <% else %>
      <thead class="table-light">
        <tr>
          <th scope="col" rowspan="2">ID:</th>
          <th scope="col" rowspan="2">Username:</th>
          <% if admin %>
            <th scope="col" rowspan="2">Email:</th>
          <% end %>
          <th scope="col" colspan="<%= admin ? 3 : 1 %>"
            rowspan="<%= admin ? 1 : 2 %>" class="text-center">Models:</th>
          <th scope="col" colspan="2" class="text-center">Social:</th>
          <th scope="col" rowspan="2">Joined:</th>
          <% if admin %>
            <th scope="col" rowspan="2">Updated:</th>
          <% end %>
          <th scope="col" rowspan="2"></th>
        </tr>
        <tr>
          <% if admin %>
            <th scope="col"># Public</th>
            <th scope="col"># Private</th>
            <th scope="col"># Followers</th>
          <% end %>
          <th scope="col"># Following:</th>
          <th scope="col"># Followers:</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr class="pb-2">
            <td scope="row"><%= user.id %></td>
            <td><%= user.username %></td>
            <% if admin %>
              <td><%= user.email %></td>
            <% end %>
            <% if admin %>
              <td><%= getPublicModelsForUser(user).count %></td>
              <td><%= getPrivateModelsForUser(user).count %></td>
              <td><%= getFollowingModelsForUser(user).count %></td>
            <% else %>
              <td><%= getModelsVisibleForUser(user).count %></td>
            <% end %>
            <td><%= getFollowingForUser(user).count %></td>
            <td><%= getFollowersForUser(user).count %></td>
            <td><%= formatTime(user.created_at) %></td>
            <% if admin %>
              <td><%= formatTime(user.updated_at) %></td>
            <% end %>
            <td class="text-end">
              <%= link_to user, class: "btn btn-success btn-sm",
                'aria-label' => "Visit #{user.username}'s profile" do %>
                <i class="bi bi-person-fill"></i>
              <% end %>  
            </td>
          </tr>
        <% end %>
        <% if @users.size < 10 %>
            <% (10-@users.size).times do %>
              <tr class="borderless-cell" style="visibility: hidden;"><td class="borderless-cell" style="visibility: hidden;">blank</td></tr>
            <% end %>
        <% end %>
      </tbody> 
    <% end %>
  </table>
  <div class="flex-grow-1"></div>
  <div class="d-flex justify-content-center">
    <%= paginate @users,
          param_name: :page,
          theme: 'bootstrap-5',
          pagination_class: "pagination-sm flex-wrap justify-content-center",
          nav_class: "d-inline-block"
    %>
  </div>   
</div>

app/views/users/show.html.erb
<div class="w-100 user-page h-100">
  <div id="userInfo" class="h-100">
    <%# display user info & allow them to update their details %>
    <div class="d-flex h-100">
      <div class="d-flex h-100 flex-column w-25">
        <div class="d-flex justify-content-between">
          <h5 class="mt-1">Account details:</h5>
          <% if @user.canModify %>
            <button class="btn btn-primary btn-sm" id="edit-button" onclick="toggleEdit()">Edit details</button>
          <% end %>
        </div>
        
        <hr class="my-2">

        <% if @user.canModify %>
          <%= render "edit" %>
        <% else %>
          <%= render "stats" %>
        <% end %>
      </div>

      <div class="d-flex flex-column pl-2 ml-2 w-50 border-start border-black">
        <div class="d-flex justify-content-between align-items-baseline">
          <h5 class="mt-1"><%= @viewingSelf ? "My" : "#{@user.username}'s"%> models:</h5>
          <p class="mb-1 pb-1 pl-3">Viewing <%= @currentlyViewing %>.</p>
        </div>

        <%= render "fmodels/tabulated", origin: "user", user: @user, editable: @editable %>

      </div>

      <div class="d-flex flex-column pl-2 ml-2 w-25 border-start border-black">
        <div class="d-flex justify-content-between w-100 mb-2">
          <ul class="nav nav-pills nav-fill flex-sm-row w-100" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <a class="nav-link <%= "active" if @activeTab == "following" %>" id="following-tab" data-bs-toggle="tab"
                data-bs-target="#following" type="button" role="tab" aria-controls="following"
                aria-selected="true">
                <%= "#{@followingTotal} " %>Following:</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link <%= "active" if @activeTab == "followers" %>" id="followers-tab" data-bs-toggle="tab"
                data-bs-target="#followers" type="button" role="tab" aria-controls="followers"
                aria-selected="false">
                <%= "#{@followersTotal} "%>Followers:</a>
            </li>
          </ul>
        </div>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade <%= "show active" if @activeTab == "following" %>" id="following" role="tabpanel" aria-labelledby="following-tab">
            <%= render "followers", tab: "following", users: @following %>
          </div>

          <div class="tab-pane fade <%= "show active" if @activeTab == "followers" %>" id="followers" role="tabpanel" aria-labelledby="followers-tab">
            <%= render "followers", tab: "followers", users: @followers %> 
          </div>
        </div>
    </div>
  </div>

</div>

<script>
  function toggleEdit() {
    console.log("Toggling editable details");

    button = document.getElementById("edit-button");

    
    let emailUname = [
      document.getElementById("user_email"),                        // email
      document.getElementById("user_username")                      // uname
    ];

    let emailUnameDefaultVals = [
      "<%= @user.email %>",
      "<%= @user.username %>"
    ];

    let emailUnameLabels = [
      document.getElementById("user_email_label"),                  // emailLabel
      document.getElementById("user_username_label")                // unameLabel
    ];
    
    // fields to hide
    let fields = [
      document.getElementById("user_password"),                     // pass 
      document.getElementById("user_password_confirmation"),        // passConf      
      document.getElementById("user_current_password")              // currentPass
    ];

    // labels
    let labels = [
      document.getElementById("user_password_label"),               // passLabel
      document.getElementById("user_password_confirmation_label"),  // passConfLabel
      document.getElementById("user_current_password_label")        // currentPassLabel
    ];

    let decorators = [
      document.getElementById("submit"),            // submit button
      document.getElementById("delete"),            // delete button
      document.getElementById("separator1"),        // upper <hr>
      document.getElementById("separator2"),        // lower <hr>
      document.getElementById("passwordHelp"),      // password change message
      document.getElementById("confirm")            // need pass to confirm message
    ]

    // are they currently editable?
    if (button.textContent == "Edit details") {
      console.log("Currently hidden. Showing...");
      
      for (var i in fields) {
        labels[i].hidden = false;
        fields[i].hidden = false;
        fields[i].disabled = false;
      }

      emailUname.forEach(field => {
        field.disabled = false;
      });

      for (var i in decorators) {
        decorators[i].hidden = false;
        decorators[i].style.display = "block";
        decorators[i].disabled = false;
      }

      // submitButton.hidden = false;
      // separatorTop.style.display = "block";
      // separatorBottom.style.display = "block";

      button.textContent = "Cancel"
      button.classList.remove("btn-primary");
      button.classList.add("btn-warning");

    } else {
      console.log("Currently shown. Hiding...");
      
      for (var i in fields) {
        labels[i].hidden = true;
        fields[i].hidden = true;
        fields[i].disabled = true;
        fields[i].value = '';
      }
      
      for (var i in emailUname){
        emailUname[i].disabled = true;
        emailUname[i].value = emailUnameDefaultVals[i];
      }

      for (var i in decorators) {
        decorators[i].hidden = true;
        decorators[i].style.display = "none";
        decorators[i].disabled = true;
      }

      // submitButton.hidden = true;
      // separatorTop.style.display = "none";
      // separatorBottom.style.display = "none";

      button.textContent = "Edit details"
      button.classList.remove("btn-warning");
      button.classList.add("btn-primary");
    }
  }
</script>