config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  devise_for :users, controllers: { 
                                :sessions => "users/sessions",
                                :registrations => "users/registrations"
                                  }
  resources :fmodels
  resources :users, :only => [:show, :index]
  # resources :follows, only: [:destroy, :create] # allows following/unfollowing
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "index#index"

  match '/users/:id', to: 'users#show', via: 'get'
  # destroy user
  match '/users/:id', to: 'users#destroy', via: 'delete'
  match '/follows', to: 'follows#create', via: 'post'
  match '/follows/:id', to: 'follows#create', via: 'post'
  match '/follows/:id', to: 'follows#destroy', via: 'delete'

  get 'fmodels/:id/analysis', to: 'fmodels#analysis', as: 'analysis_results'

end

app/controllers/fmodels_controller.rb
class FmodelsController < ApplicationController
  before_action :set_fmodel, only: %i[ show edit update destroy analysis ]
  helper_method :getTableHeaders
  # before_action :set_title

  # GET /fmodels or /fmodels.json
  def index
    if helpers.admin
      @fmodels = Fmodel.all # all
    else
      @fmodels = Fmodel.where(visibility: "global") # all public
    end

    if params[:search].present? && params[:search] != ""
      @fmodels = @fmodels.where("LOWER(title) LIKE :search", search: "%#{params[:search].downcase}%")
    end

    if params[:sort].present?
      case params[:sort]
      when "date_created_asc"
        @fmodels = @fmodels.order(:created_at)
      when "date_created_desc"
        @fmodels = @fmodels.order(created_at: :desc)
      when "last_updated_asc"
        @fmodels = @fmodels.order(:updated_at)
      when "last_updated_desc"
        @fmodels = @fmodels.order(updated_at: :desc)
      when "title_asc"
        @fmodels = @fmodels.order("LOWER(title)")
      when "title_desc"
        @fmodels = @fmodels.order("LOWER(title) DESC")
      end
    end

    totalFmodels = @fmodels.size

    @fmodels = Kaminari.paginate_array(@fmodels).page(params[:page])

    current_page_range = (@fmodels.offset_value + 1)..(@fmodels.offset_value + @fmodels.length)
    @currentlyViewing = "#{current_page_range.first}-#{current_page_range.last} of #{totalFmodels}"

    @title = "Feature Model Database"
    @header = "Feature Models"

    @hasReturn = true

    @hasSearch = true
    @searchObject = "Feature Models"
    @placeholder = "Input title..."

    @hasDropdown = true
    @dropdownOptions = {
      "Date created (Ascending)" => "date_created_asc",
      "Date created (Descending)" => "date_created_desc",
      "Last updated (Ascending)" => "last_updated_asc",
      "Last updated (Descending)" => "last_updated_desc",
      "Title (A-Z)" => "title_asc",
      "Title (Z-A)" => "title_desc"
    }

    @path = fmodels_path
  end

  # GET /fmodels/1 or /fmodels/1.json
  def show
    @title = @fmodel.title
    @header = @fmodel.title

    @creator = @fmodel.getCreator

    @hasReturn = true

    @hasAnalysisButton = true

    # analysis(@fmodel)
    flash[:origin] = request.referer
  end

  # GET /fmodels/new
  def new
    @fmodel = Fmodel.new
    @title = "Create New Feature Model"
    @header = "Create New Feature Model"
    
    # to show return button and instructions on creation form
    @hasReturn = true
    @instructions = true
  end

  # GET /fmodels/1/edit
  def edit
    if current_user.present? && @fmodel.canModify
      @title = "Editing: " + @fmodel.title
      @header = "Editing: " + @fmodel.title

      @instructions = true
      @hasReturn = true
    else
      redirect_back fallback_location: root_path, flash: { alert: "You do not have permission to edit this feature model." } and return
    end
  end

  # POST /fmodels or /fmodels.json
  def create
    @fmodel = Fmodel.new(fmodel_params)

    puts "Current user: #{current_user}"
    @fmodel.created_by = current_user.present? ? current_user.id : ""

    message = validateModel(@fmodel)

    respond_to do |format|
      if message != ""
        Rails.cache.write("graph_data", @fmodel.graph)
        # print graph data from cache
        puts "Graph data from cache: #{Rails.cache.read("graph_data")}"
        session[:title] = @fmodel.title
        session[:notes] = @fmodel.notes
        session[:visibility] = @fmodel.visibility
        format.html {
          redirect_back fallback_location: root_path, alert: message and return }
        format.json { render json: { error: message }, status: :unprocessable_entity and return }
      else
        if @fmodel.save
          format.html { redirect_to '/fmodels', notice: "#{@fmodel.title} saved!" }
          format.json { render :show, status: :created, location: @fmodel }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @fmodel.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /fmodels/1 or /fmodels/1.json
  def update
    @fmodel = Fmodel.find(params[:id])
    @newFmodel = Fmodel.new(fmodel_params)

    message = validateModel(@newFmodel)

    respond_to do |format|
      if message != ""
        Rails.cache.write("graph_data", @newFmodel.graph)
        # print graph data from cache
        puts "Graph data from cache: #{Rails.cache.read("graph_data")}"
        session[:title] = @newFmodel.title
        session[:notes] = @newFmodel.notes
        session[:visibility] = @newFmodel.visibility
        format.html {
          redirect_back fallback_location: root_path, alert: message and return }
        format.json { render json: { error: message }, status: :unprocessable_entity and return }
      else
        if @fmodel.update(fmodel_params)
          format.html { redirect_to fmodel_url(@fmodel), notice: "#{@fmodel.title} updated!" }
          format.json { render :show, status: :ok, location: @fmodel }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @fmodel.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /fmodels/1 or /fmodels/1.json
  def destroy
    title = @fmodel.title
    @fmodel.destroy!

    respond_to do |format|
      format.html {
        if request.referer && request.referer.include?("fmodels/#{params[:id]}")
          puts "redirecting from model show page, redirecting to #{flash[:origin]}"
          redirect_to flash[:origin], notice: "#{title} deleted!"
          # redirect_back(fallback_location: root_path, notice: "#{title} deleted!", allow_other_host: false)
        else
          puts "redirecting from elsewhere"
          redirect_back(fallback_location: root_path, notice: "#{title} deleted!")
        end
      }
      format.json { head :no_content }
    end
  end

  # perform analysis for display to the user
  def analysis
    $interrupt_flag = false
    @features = Array.new
    links = Array.new
    ctcs = Array.new

    consistent = Fmodel.parseJson(@fmodel.graph, @features, links, ctcs)  # create programmatic representation of fmodel
    Fmodel.printFeatures(@features)
    puts "consistent: #{consistent}"

    # define feature model metrics
    @numFeatures = @features.size - 1    # remove -1?
    @numOptional = 0
    @numMandatory = 0
    @numAlternative = 0
    @numOr = 0
    @rootFeature = nil
    @numConstraints = ctcs.size

    # iterate through all features and increment above metrics accordingly
    @features.each do |f|
      if (f.status == "Optional")
        @numOptional += 1
      elsif (f.status == "Mandatory")
        @numMandatory += 1
      elsif (f.status == "Alternative")
        @numAlternative += 1
      elsif (f.status == "Or")
        @numOr += 1
      elsif (f.status == "Root")  # obtain root feature
        @rootFeature = f
      end
    end

    puts "getting depth..."
    @depth = treeDepth(@rootFeature, @features)   # bfs to find tree depth
    puts "depth: #{@depth}"
    puts "getting leaves..."
    @leaves = getLeaves(@rootFeature, @features)  # dfs to find leaves
    puts "leaves gotten!"

    getTableHeaders()
    puts "headers gotten!"
    # perform configurations job
    # @validConfigs = ValidConfigsJob.perform_async(@features, @leaves, @depth, ctcs, @rootFeature)
    @validConfigs = getValidConfiguations(ctcs)
    puts "valid configs gotten!"
    
    @coreFeatures = Array.new
    @voidFeatures = Array.new

    
    # format configurations for display in table
    #   - trim 
    
    
    # puts "\nleaves:"
    # @leaves.each do |l|
    #   print "#{l.name}  "
    # end
    # puts "\n"

    getConfigsForPrinting()
    puts "got everything ready"

    getCoreAndVoid()
    puts "got core and void. finishing..."
    # getVoidFeatures()

    # puts "\n\ntable headers:"
    # # puts "depth: #{@depth-1}"
    # @tableHeaders.each do |t| 
    #   # puts "\n"
    #   t.each_with_index do |r, index|
    #     if (index == @depth - 1)
    #       print "#{r.name} "
    #     end
    #   end
    # end
    # puts "\n"
    ctcs.each do |c|
      x = c.requires ? "requires" : "excludes"
      puts "#{Fmodel.findFeatureFromKey(@features, c.from).name} #{x} #{Fmodel.findFeatureFromKey(@features, c.to).name}"
    end

    render json: {
      analysis_complete: true,
      num_features: @numFeatures,
      num_optional: @numOptional,
      num_mandatory: @numMandatory,
      num_alternative: @numAlternative,
      num_or: @numOr,
      num_constraints: @numConstraints,
      depth: @depth,
      valid_configs_size: @validConfigs.size,
      core_features: @coreFeatures,
      void_features: @voidFeatures,
      leaves: @leaves,
      table_headers: @tableHeaders,
      configs: @configsTableFormat,
    }
  end

  private
    def validateModel(fmodel)
      # parse for errors
      @features = Array.new
      links = Array.new
      ctcs = Array.new

      errors = Fmodel.parseJson(@fmodel.graph, @features, links, ctcs)

      puts "model parsed. Verifying..."

      # reject fmodel if:
      # has only one feature
      # has no links
      # has any disconnected links
      # has any disconnected features
      message = ""

      if @features.size < 2
        message = "#{ @features.size == 0 ? "No" : "Only #{@features.size}"} feature#{@features.size == 1 ? "" : "s"} found. Please increase the size of your model."
      elsif links.size == 0
        message = "No links found. Please connect your features."
      else
        if !errors.empty?
          # errors found during parsing
          puts "Error found in parsing. Origin: #{errors.values[0]}"
          message = errors.values[1]
        end
        # check for disconnected features
        @features.each do |f|
          if (f.children.size == 0 && f.parent.nil?)
            message = "Feature #{f.name} is not connected."
          end
        end
      end
      message
    end

app/helpers/fmodels_helper.rb
module FmodelsHelper
end

app/views/fmodels/_actual-table.html.erb
<table class="w-100 table table-sm table-hover"></table>
  <% if fmodels.size == 0 %>
    <tr>
    <% if origin == "index" %>
      <td>No feature models found. Make one and add to the database!</td>
    <% else %>
        <td>
          <%= @current_user.present? && (@user.id == @current_user.id) ? "You haven't " : "#{@user.username} hasn't "%>
          made any feature models yet.  
        </td>
    <% end %>
    </tr>
  <% else %>
    <thead class="table-light">
      <th scope="col">Title:</th>
      <% if origin != "user" %>
        <th scope="col">Created by:</th>
      <% end %>
      <th scope="col">Created:</th>
      <th scope="col">Updated:</th>
      <% if editable %>
        <th scope="col">Visibility:</th>
      <% end %>
      <th scope="col" colspan="3"
        class="text-end">Actions:</th>
      <%# <th scope="col"></th>
      <th scope="col"></th> %>
    </thead>
    <tbody>
      <% fmodels.each do |fmodel| %>
        <tr class="pb-2">
          <td scope="row"><%= fmodel.title %></td>
          <% if origin != "user" %>            
            <td><%= fmodel.getCreator %></td>
          <% end %>  
          <td><%= formatTime(fmodel.created_at) %></td>
          <td><%= formatTime(fmodel.updated_at) %></td>
          <% if editable %>
            <td><%= fmodel.getVisibility %></td>
          <% end %>
          <td colspan="1" class="text-end">
            <%= link_to fmodel, class: "btn btn-success btn-sm" do %>
              <i class="bi bi-search"></i>
            <% end %>  

            <% if editable %>
              <%= link_to edit_fmodel_path(fmodel), class: "btn btn-warning btn-sm" do %>
                <i class="bi bi-pencil"></i>
              <% end %>

              <form class="delete-form" action="<%= fmodel_path(fmodel) %>" method="post" style="display: none;">
                <input type="hidden" name="_method" value="delete">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              </form>

              <button type="button" class="btn btn-danger btn-sm delete-button">
                <i class="bi bi-x-lg"></i>
              </button>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% if fmodels.size < 10 %>
          <% (10-fmodels.size).times do %>
            <tr class="borderless-cell" style="visibility: hidden;"><td class="borderless-cell" style="visibility: hidden;">blank</td></tr>
          <% end %>
      <% end %>
    </tbody> 
  <% end %>
</table>
<div class="flex-grow-1"></div>
<div class="d-flex justify-content-center">
  <%= paginate fmodels,
        param_name: (origin == "user" ? pager : :page),
        theme: 'bootstrap-5',
        pagination_class: "pagination-sm flex-wrap justify-content-center",
        nav_class: "d-inline-block"
  %>
</div>

<script>
  document.querySelectorAll('.delete-button').forEach(button => {
    button.addEventListener('click', function() {
      if (confirm("Are you sure?")) {
        const form = this.previousElementSibling;
        form.submit();
      }
    });
  });
</script>

app/views/fmodels/_fmodel.html.erb
<%= render "fmodel-graph", fmodel: @fmodel %>

app/views/fmodels/_form.html.erb
<%= form_with(model: fmodel, html: {id: "form", class: "d-flex"}) do |form| %>

  <div id="left-panel" class="w-25 mw-25">
    
    <%# title text field %>
    <div class="field form-floating" >
      <%= form.text_field :title,
        :required => true,
        :placeholder => "Feature model title...",
        value: (session[:title].present? ? session[:title] : (fmodel.title if fmodel.title.present?)),
        class: "form-control mb-2"
      %>
      <%= form.label :title %>
    </div>

    <%# notes text field %>
    <div class="field form-floating">
      <%= form.text_area :notes,
        :placeholder => "Feature model notes...",
        value: (session[:notes].present? ? session[:notes] : (fmodel.notes if fmodel.notes.present?)),
        class: "form-control mb-2",
        style: "resize: none; height: 100%;"
      %>
      <%= form.label :notes %>
    </div>

    <%# make model visibility dropdown - !! invisible and set to public for guests !! %>
    <div class="field row g-2 align-items-baseline d-flex <%= "d-none" if !current_user.present? %>">
      <div class="col-auto ml-3">
        <%= form.label :visibility, "Model Visibility", class: "col-form-label" %>
      </div>
      <div class="col-auto flex-grow-1 mr-3">
        <%= form.select :visibility, {
          "Public" => "global",
          "Private" => "unlisted", 
          "Followers" => "followers"
          },
          { include_blank: false, selected: session[:visibility].presence || @fmodel&.visibility.presence || "global" },
          class: "form-select mb-2",
          disabled: !current_user.present?
          %>
      </div>
    </div>

    <%# clean variables from session %>
    <% session.delete(:title) %>
    <% session.delete(:notes) %>
    <% session.delete(:visibility) %>

    <%# hidden graph json text field %>
    <div>
      <%= form.label :graph, style: "display: none" %>
      <%= form.text_field :graph, style: "display: none" %>
    </div>

    <%# hidden userID text field %>
    <div>
      <%= form.label :created_by, style: "display: none" %>
      <%= form.text_field :created_by, style: "display: none" %>
    </div>

    <%# interaction buttons %>
    <div class="d-flex align-items-end">
      <div class="d-flex">
        <%# import %>
        <div>
          <button onclick="importModel()" type="button" title="Import model as JSON"
            class="btn btn-primary mr-2"><i class="bi bi-upload"></i></button>
          
        </div>

        <%# export %>
        <div>
          <button onclick="exportModel()" type="button" title="Export diagram as JSON"
            class="btn btn-primary"><i class="bi bi-download"></i></button>
          
        </div>
      </div>

      <%# submit %>
      <% buttonText = controller.action_name == "edit" ? "Edit" : "Create" %>
      <%= form.submit buttonText, :class => 'btn btn-success ml-auto' %>
    </div>

    <%# show instructions to user %>
    <% if @instructions %>
      <hr class="">
      <h6>Instructions:</h6>
      <ul class="instruction-text">
        <li>Right-click to create a new feature or drag from the palette.</li>
        <li>Double click a feature to edit its text.</li>
        <li>Draw links by dragging from the palette or hovering over a node and holding left click.</li>
        <li>Right-click on links to toggle requirement status or make into a Cross-Tree Constraint.</li>
        <li>Ctrl+Z and Ctrl+Y can be used to undo and redo.</li>
        <li>Import/export a model as a JSON using the blue buttons above.</li>
      </ul>
    <% end %>
  </div>
  <%# , class: "btn btn-outline-success" %>

  <div id="right-panel" class="w-75 ml-2 left-border">
    <div>
      <%= render "fmodel-graph", fmodel: @fmodel %>
    </div>
  </div>

  <script>
    function importModel() {
      let importedJson = prompt("Please input a valid JSON format", "");
      if (importedJson == "") {
        alert("No input detected, please try again.");
      } else {
        diagram.model = go.Model.fromJson(importedJson);
        loadDiagramProperties();
      }
    }

    function exportModel() {
      saveDiagramProperties();
      navigator.clipboard.writeText(diagram.model.toJson());
      alert("Copied model to clipboard!");
    }

    function saveDiagramProperties() {
      diagram.model.modelData.position = go.Point.stringify(diagram.position);
    }

    function loadDiagramProperties(e) {
      var pos = diagram.model.modelData.position;
      if (pos) diagram.position = go.Point.parse(pos);
    }

    var form = document.getElementById('form');
    
    form.addEventListener('submit', function(event) {
      document.getElementById("fmodel_graph").value = diagram.model.toJson(); 

      if (document.getElementById("fmodel_graph").value === '{ "class": "GraphLinksModel",  "nodeDataArray": [],  "linkDataArray": []}') {
        event.preventDefault(); // prevents form being submitted if diagram blank
        alert("Please create a Feature Model using the diagram builder.");
      };
    });
  </script>
<% end %>

app/views/fmodels/_tabulated.html.erb
<table class="w-100 table table-sm table-hover">
  <% if @fmodels.size == 0 %>
    <tr>
    <% if origin == "index" %>
      <td>No feature models found. Make one and add to the database!</td>
    <% else %>
        <td>
          <%= @current_user.present? && (@user.id == @current_user.id) ? "You haven't " : "#{@user.username} hasn't "%>
          made any feature models yet.  
        </td>
    <% end %>
    </tr>
  <% else %>
    <thead class="table-light">
      <th scope="col">Title:</th>
      <% if origin != "user" %>
        <th scope="col">Created by:</th>
      <% end %>
      <th scope="col">Created:</th>
      <th scope="col">Updated:</th>
      <% if editable %>
        <th scope="col">Visibility:</th>
      <% end %>
      <th scope="col" colspan="3"
        class="text-end">Actions:</th>
      <%# <th scope="col"></th>
      <th scope="col"></th> %>
    </thead>
    <tbody>
      <% @fmodels.each do |fmodel| %>
        <tr class="pb-2">
          <td scope="row"><%= fmodel.title %></td>
          <% if origin != "user" %>            
            <td><%= fmodel.getCreator %></td>
          <% end %>  
          <td><%= formatTime(fmodel.created_at) %></td>
          <td><%= formatTime(fmodel.updated_at) %></td>
          <% if editable %>
            <td><%= fmodel.getVisibility %></td>
          <% end %>
          <td colspan="1" class="text-end">
            <%= link_to fmodel, class: "btn btn-success btn-sm",
                'aria-label' => "View #{fmodel.title}"  do %>
              <i class="bi bi-search"></i>
            <% end %>  

            <% if editable %>
              <%= link_to edit_fmodel_path(fmodel), class: "btn btn-warning btn-sm",
                'aria-label' => "Edit #{fmodel.title}" do %>
                <i class="bi bi-pencil"></i>
              <% end %>

              <form class="delete-form" action="<%= fmodel_path(fmodel) %>" method="post" style="display: none;">
                <input type="hidden" name="_method" value="delete">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              </form>

              <button type="button" class="btn btn-danger btn-sm delete-button"
                aria-label="Delete <%= fmodel.title %>">
                <i class="bi bi-x-lg"></i>
              </button>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% if @fmodels.size < 10 %>
          <% (10-@fmodels.size).times do %>
            <tr class="borderless-cell" style="visibility: hidden;"><td class="borderless-cell" style="visibility: hidden;">blank</td></tr>
          <% end %>
      <% end %>
    </tbody> 
  <% end %>
</table>
<div class="flex-grow-1"></div>
<div class="d-flex justify-content-center">
  <%= paginate @fmodels,
        param_name: (origin == "user" ? :models_page : :page),
        theme: 'bootstrap-5',
        pagination_class: "pagination-sm flex-wrap justify-content-center",
        nav_class: "d-inline-block"
  %>
</div>

<script>
  document.querySelectorAll('.delete-button').forEach(button => {
    button.addEventListener('click', function() {
      if (confirm("Are you sure?")) {
        const form = this.previousElementSibling;
        form.submit();
      }
    });
  });
</script>

app/views/fmodels/edit.html.erb
<%# <h1>Editing fmodel</h1> %>

<%= render "form", fmodel: @fmodel %>

app/views/fmodels/index.html.erb
<%# < style="color: green"><%= notice %>

<div id="fmodels">
  <%= render "tabulated", origin: "index", editable: admin %>
</div>

app/views/fmodels/new.html.erb
<div class="">
  <%= render "form", fmodel: @fmodel %>
</div>