config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  devise_for :users, controllers: { 
                                :sessions => "users/sessions",
                                :registrations => "users/registrations"
                                  }
  resources :fmodels
  resources :users, :only => [:show, :index]
  # resources :follows, only: [:destroy, :create] # allows following/unfollowing
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "index#index"

  match '/users/:id', to: 'users#show', via: 'get'
  # destroy user
  match '/users/:id', to: 'users#destroy', via: 'delete'
  match '/follows', to: 'follows#create', via: 'post'
  match '/follows/:id', to: 'follows#create', via: 'post'
  match '/follows/:id', to: 'follows#destroy', via: 'delete'

  get 'fmodels/:id/analysis', to: 'fmodels#analysis', as: 'analysis_results'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @title %> | SPO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/gojs/release/go.js"></script>

  
  </head>

  <body class="mx-auto white">

    <header class=
      "mx-auto d-flex justify-content-between
      align-items-center bottom-border py-2">
      <div class="ml-3 pl-3">
        <%= link_to "Software Products Online", "/", class: "header-title" %>
      </div>

      <div class="mr-3 pr-3 d-flex align-items-center h-100">
        <% if !user_signed_in? %>
          <p class="mb-0 mr-2">Browsing as guest.</p>
        <% elsif user_signed_in? %>
          <p class="mb-0 mr-2">
            Signed in as <%= current_user.username %><%= current_user.isAdmin ? " (admin)." : "." %>
          </p>
        <% end %>
        <%= button_to "Browse users", users_path, method: :get, class: "btn btn-primary mr-2" %>
        <%= button_to "View Models", fmodels_path, method: :get, class: "btn btn-primary mr-2" %>
        <%= button_to "New", new_fmodel_path, method: :get, class: "btn btn-primary mr-2" %>
        <% if user_signed_in? %>
          <%= button_to "Profile", user_path(current_user), method: :get, class: "btn btn-primary mr-2" %>
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger mr-2" %>
        <% else %>
          <%= button_to "Login", new_user_session_path, method: :get, class: "btn btn-primary" %>
        <% end %>
      </div>
    </header>

    <main class="px-5 py-2 mx-auto">
      <%# <script>
        
        document.addEventListener("DOMContentLoaded", function() {
          
        })
      </script> %>

      <% if !@centreDiv %>
        <div class="centre-box p-3">
          <div>
            <div class="bottom-border mb-2 d-flex justify-content-between">
              <div class="d-flex align-items-center">
                <h2 class="pb-1"><%= @header %></h2>
                <% if (controller.controller_name == "users" || controller.controller_name == "fmodels") && controller.action_name == "index" %>
                  <p class="mb-1 pb-1 pl-3">Viewing <%= @currentlyViewing %>.</p>
                <% end %>
              </div>
              <div class="d-flex mr-3">
                <% if @hasSearch %>
                  <div class="mr-4">
                    <%= form_tag @path, method: :get, class: "row g-3 align-items-center" do %>
                      <div class="col-auto">
                        <%= label_tag :search, "Search:", class: "col-form-label" %>
                      </div>
                      <div class="col-auto">
                        <%= text_field_tag :search, params[:search], class: "form-control mr-2", placeholder: @placeholder %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
                <% if @hasDropdown %>
                  <div class="pl-2">
                    <%= form_tag @path, method: :get, class: "row g-2 align-items-center" do %>
                      <%= hidden_field_tag :search, params[:search], id: "search-hidden" %>
                      <div class="col-auto">
                        <%= label_tag :sort, "Sort by:", class: "col-form-label" %>
                      </div>
                      <div class="col-auto">
                        <%= select_tag :sort, options_for_select(@dropdownOptions, params[:sort]), class: "form-select mr-2" %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
                <% if @hasAnalysisButton %>
                  <button id="analysis-button" class="btn btn-primary mb-3 h-75">Start Analysis</button>
                <% end %>
                <% if @hasReturn %>
                  <div>
                    <%= link_to 'Back', 'javascript:history.back()', class: "btn btn-dark mb-3 ml-4" %>
                  </div>
                <% end %>
              </div>
            </div>
            <%= yield %>
          </div>
        </div>
      <% else %>
      <% end %>

      <div class="toast-container position-fixed  bottom-0 start-50 translate-middle-x p-3" style="z-index: 11">
        <div class="toast toast-notif" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header justify-content-between bg-danger text-white">
            <strong>Alert!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body">
            <% puts alert&.kind_of?(Array) %>
            <p class="alert toast-text p-0">
              <% if alert&.kind_of?(Array) %>
                <%= alert&.to_sentence(words_connector: ', ', two_words_connector: ', ', last_word_connector: ', ') %>
              <% else %>
                <%= alert %>
              <% end %>
            </p> 
          </div>
        </div>

        <div class="toast toast-notif" role="notice" aria-live="assertive" aria-atomic="true">
          <div class="toast-header justify-content-between bg-success">
            <strong>Notice:</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body">
            <p class="notice toast-text">
              <% if notice&.kind_of?(Array) %>
                <%= notice&.to_sentence(words_connector: ', ', two_words_connector: ', ', last_word_connector: ', ') %>
              <% else %>
                <%= notice %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </main>

    <script>

      if (document.readyState !== 'loading') {
          console.log('document is already ready, just execute code here');
          toasts();
          <% if @hasSearch && @hasDropdown %>
            dropdowns();
          <% end %>
      } else {
          document.addEventListener('DOMContentLoaded', function () {
            console.log('document was not ready, place code here');
            toasts();
            <% if @hasSearch && @hasDropdown %>
              dropdowns();
            <% end %>
          });
      }

      function toasts() {
        var toastElList = [].slice.call(document.querySelectorAll('.toast'))
        var toastList = toastElList.map(function (toastEl) {
          return new bootstrap.Toast(toastEl, { 
            animation: true,
            // autohide: false, // for debugging
            delay: 10000
          });
        });

        var noticeList = document.querySelectorAll('.toast-text');
  
        // console.log(document.getElementsByClassName('toast'));
  
        for (var i in toastList) {
          console.log(noticeList[i].innerHTML.trim().length);
          console.log(noticeList[i].innerHTML.trim() === "");

          if (noticeList[i].innerHTML.trim() != "") {
            toastList[i].show();
          }
        }
      }

      function dropdowns() {
        const sortSelect = document.querySelector('#sort');
        const search = document.querySelector('#search');
        const searchHidden = document.querySelector('#search-hidden');
        sortSelect.addEventListener('change', function() {
          const form = this.form;
          console.log("changed");
          // make the value of hidden_field_tag :search, params[:search] the value of search
          searchHidden.value = search.value;
          // submit the form
          form.submit();
        });
      }



      // document.addEventListener('DOMContentLoaded', function() {
        
      // });
    </script>

  </body>
</html>